name: rename
description: Helps you to change or rename your flutter project BundleId and AppName for Ios, Android, MacOS and Linux platforms
version: 2.0.1
homepage: https://github.com/onatcipli/rename.git

environment:
  sdk: '>=2.14.0 <3.0.0'

executables:
  rename:

dependencies:
  args: ^2.3.0
  logger: ^1.1.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.18.2
