name: rename
description: A sample command-line application that rename flutter application name.
version: 1.0.7
homepage: https://github.com/onatcipli/rename.git
author: Onat Cipli <ciplionat35@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

executables:
  rename:

dependencies:
  args: ^1.5.2

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
